org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

systemProp.https.protocols=TLSv1.2,TLSv1.3

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.76
neo_version_range=[26.1.2,)

mod_version=1.5.1
mod_id=maple_banktrade
mod_name=Maple-BankTrade
mod_group_id=com.maple.maple_banktrade
mod_description=Bank · Bank Card · Wallet · Trade
mod_url=https://github.com/wanggugu197/Maple-BankTrade
mod_issue_tracker=https://github.com/wanggugu197/Maple-BankTrade/issues
mod_authors=maple197
mod_license=GNU Lesser General Public License v3
